kind: pipeline
type: docker
name: default

steps:
  - name: lint
    image: node:12-alpine
    environment:
      NODE_ENV: development
    commands:
      - npm ci
      - npm run lint

  - name: test
    image: node:12-alpine
    environment:
      NODE_ENV: development
    commands:
      - npm test

  - name: publish
    image: riscue/drone-img
    settings:
      auto_tag: true
      username: riscue
      password:
        from_secret: DOCKER_PASSWORD
    when:
      event:
        - tag
